const STRINGS = {
  option1Desc: `Pump up your hair color vibrancy with this professional formula for colored hair. Enriched with resveratrol and powerful polyphenol, which work together to protect the hair color from fading for up to 8 weeks, and protects hair fiber from damage.`,
  option2Desc: `Enhance and illuminate blonde hair, enriched with Polyphenol derived from Açai Berry Extract and purple pigments that help to neutralize undesired yellow tones for a cool blonde effect.`,
  option3Desc: `Neutralize and illuminate your hair. Professional formula enriched with Magnesium. A combination of an anti-yellowing agent to neutralise yellow tones and leave hair feeling soft and looking shiny.`,
  option4Desc: `The 1st professional haircare range that renews lengths and fills-in ends, powered by the combination of an exclusive patented thickening technology Filler-A100 + Amino Acids. No more trade-off between length and thickness!`,
  option5Desc: `Discover the gold standard of professional repair.`,
  option6Desc: `Strengthening anti-breakage for normal to fragile hair. Enriched with vitamin B6 and Biotin, for instant reduction of breakage.`,
  option7Desc: `For frizzy or rebellious hair! Enriched with Pro- Keratin, Kukui Nut Oil and Evening primrose oil. The penetrating oils enables the facilitation of smoother, stronger hair and provides you with a long-lasting, anti-humidity shield which controls your hair and keeps it frizz free. `,
  option8Desc: `Professional formula enriched with glycerol and coconut oil, offers just the right dose of nourishment to dry hair. Glycerol helps to hydrate and nourish, while coconut oil brings shine to the hair.`,
  option9Desc: `Give your hair an anti-gravity effect that boosts your hair volume. Hair looks volumised, with an added texture without weighing it down. `,
  option1Match: `Vitamino Color`,
  option2Match: `Blondifier`,
  option3Match: `Silver`,
  option4Match: `Pro Longer`,
  option5Match: `Absolute Repair`,
  option6Match: `Inforcer`,
  option7Match: `Liss Unlimited`,
  option8Match: `Nutrifier`,
  option9Match: `Volumetry`,
  option1Rec: `color-treated hair & sensitive colored hair.`,
  option2Rec: `Highlighted hair & Blonde color-treated hair.`,
  option3Rec: `Grey hair, Silver hair and Light blonde hair.`,
  option3RecAdd: `You will neutralize (anti-yellowing) and enhance your colour shine while softening your hair.`,
  option4Rec: `Longer the hair by renewing the length and avoid cutting the ends.`,
  option4RecAdd: `You will reduce the hair breakage & split ends reduction with a 5x shinier hair.`,
  option5Rec: `Damaged hair.`,
  option5RecAdd: `You will get a Shinier and softer hair, lightweight touch & resurfaced and less damaged hair.`,
  option6Rec: `Fragile hair prone to breakage & Weak hair.`,
  option7Rec: `Frizzy hair, Rebellious hair, Straightened hair & Coarse Hair.`,
  option7RecAdd: `You will ger a disciplined, anti frizz, anti humidity, purified and smooth hair.`,
  option8Rec: `Normal to dry hair, Dry hair & Under-Nourished hair.`,
  option8RecAdd: `You will have a nourished, softer & shinier hair.`,
  option9Rec: `Flat hair & Fine hair.`,
  option9RecAdd: `You will add volume with a root-lifting effect & your hair will feel nourished.`,
  recommendedFor: `Recommended for:`,
  question1: `What is your hair goal?`,
  question2: `What is your main care concern?`,
  choice1A: `Color Vibrancy`,
  choice2A: `Damaged Hair`,
  choice1B: `Illuminate Blonde Hair`,
  choice2B: `Weak Hair`,
  choice3A: `Neutralize Yellow Tones`,
  choice3B: `Frizzy Hair`,
  choice4A: `Longer Hair`,
  choice4B: `Dry Hair`,
  choice5A: `Healthy Hair`,
  choice5B: `Flat Hair`,
  takeQuiz: `Take the quiz`,
  shopNow: `Shop now`,
  getResults: `Get your results`,
  next: `Next`,
  quiz: `Quiz`,
  quizTitle: `L'Oréal Professionnel Hair Care Routine`,
  quizTagLine: `Discover your personalised haircare routine`,
  quizTagLineQ: `What's the best routine for your hair?`,
};

export default STRINGS;
